# Generated by Django 6.0 on 2026-01-06 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified therapists can publish blogs directly without approval'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_therapists', to=settings.AUTH_USER_MODEL),
        ),
    ]
