# Generated by Django 6.0 on 2026-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_therapistprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=17),
        ),
    ]
