# Generated by Django 6.0 on 2026-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_therapistprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_profiles/'),
        ),
    ]
