# Generated by Django 6.0 on 2026-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_therapistprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/therapist_profiles/'),
        ),
    ]
