# Generated by Django 6.0.1 on 2026-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_therapistprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='professional_documents',
            field=models.JSONField(blank=True, help_text="Array of uploaded document URLs: [{name: 'Citizenship', url: '...', type: 'citizenship', uploaded_at: '...'}]", null=True),
        ),
    ]
