# Generated by Django 6.0.1 on 2026-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_therapistprofile_professional_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='professional_documents',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload your license, degree, or other credentials', null=True, upload_to='media/therapist_certificates/'),
        ),
    ]
