# Generated by Django 6.0.1 on 2026-01-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_therapistprofile_professional_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='certificates',
        ),
        migrations.CreateModel(
            name='CertificateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload license, degree, or other credentials (PDF, DOC, DOCX, images)', upload_to='media/therapist_certificates/')),
                ('document_name', models.CharField(help_text="e.g., 'License', 'Psychology Degree', 'Certification in CBT'", max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.therapistprofile')),
            ],
            options={
                'db_table': 'therapist_certificates',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
