# Generated by Django 6.0.1 on 2026-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_therapistprofile_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded certificate documents with URLs and metadata', null=True),
        ),
        migrations.DeleteModel(
            name='CertificateDocument',
        ),
    ]
