# Generated by Django 6.0.1 on 2026-01-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_therapistprofile_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='certificates',
        ),
        migrations.CreateModel(
            name='TherapistCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='media/therapist_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.therapistprofile')),
            ],
        ),
    ]
