# Generated by Django 6.0.1 on 2026-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_therapistprofile_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload your license, degree, or other credentials', null=True, upload_to='media/therapist_certificates/'),
        ),
        migrations.DeleteModel(
            name='TherapistCertificate',
        ),
    ]
