# Generated by Django 4.2.27 on 2026-02-04 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_therapistprofile_certificates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.CharField(help_text='Comma-separated specialization tags', max_length=500)),
                ('therapy_approaches', models.CharField(help_text='Comma-separated therapy approaches (cbt, dbt, etc.)', max_length=500)),
                ('modalities', models.CharField(help_text='Comma-separated modalities (individual, couples, online, etc.)', max_length=200)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Languages spoken', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('therapist', models.OneToOneField(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist Specialization',
                'verbose_name_plural': 'Therapist Specializations',
            },
        ),
    ]
