# Generated by Django 4.2.27 on 2026-02-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_therapistspecialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TherapistSpecialization',
        ),
    ]
