# Generated by Django 6.0 on 2026-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_patientprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload your license, degree, or other credentials', null=True, upload_to='therapist_certificates/'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_profiles/'),
        ),
    ]
