# Generated by Django 4.2.27 on 2026-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_patientprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='booked_slots',
            field=models.JSONField(blank=True, default=list, help_text="List of booked slots: [{'date': '2026-02-10', 'start_time': '09:00', 'end_time': '10:00'}]", null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload your license, degree, or other credentials', null=True, upload_to='therapist_certificates/'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_profiles/'),
        ),
    ]
