# Generated by Django 4.2.27 on 2026-02-10 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_therapistprofile_booked_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='certificates',
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Auto-verified when all required documents are verified'),
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('citizenship', 'Citizenship/ID'), ('license', 'Professional License'), ('education', 'Educational Certificate'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='verification_documents/')),
                ('encrypted_file_path', models.TextField(blank=True, help_text='Encrypted file path', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('therapist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='accounts.therapistprofile')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('therapist_profile', 'document_type')},
            },
        ),
    ]
