# Generated by Django 6.0 on 2026-02-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_therapistprofile_certificates_and_more'),
        ('accounts', '0018_therapistprofile_booked_slots_and_more'),
    ]

    operations = [
    ]
