# Generated by Django 6.0.1 on 2026-01-27 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_therapistprofile_certificates_and_more'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reframe',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood_intensity',
            field=models.IntegerField(default=5, help_text='Mood intensity from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.patientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('excited', 'Excited'), ('calm', 'Calm'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('grateful', 'Grateful')], default='neutral', max_length=20),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-created_at'], name='journal_jou_created_b6c001_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['patient', '-created_at'], name='journal_jou_patient_32b184_idx'),
        ),
    ]
