# Generated by Django 6.0.1 on 2026-01-29 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_therapistprofile_certificates_and_more'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_therapists_count', models.IntegerField()),
                ('matches_generated', models.IntegerField()),
                ('processing_time_ms', models.IntegerField(help_text='Time taken to generate matches in milliseconds')),
                ('filters_applied', models.JSONField(help_text='Which filters were applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMatchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_text', models.TextField(help_text='Combined text representation of patient needs')),
                ('needs_vector', models.JSONField(blank=True, help_text='TF-IDF vector representation', null=True)),
                ('presenting_issues', models.JSONField(blank=True, help_text='Main issues patient wants to address', null=True)),
                ('preferred_therapy_approach', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_languages', models.JSONField(blank=True, null=True)),
                ('consultation_preference', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_profiles', to='surveys.survey')),
            ],
            options={
                'db_table': 'patient_match_profiles',
            },
        ),
        migrations.CreateModel(
            name='TherapistMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='TF-IDF cosine similarity score (0-1)')),
                ('specialty_match_score', models.FloatField(default=0.0, help_text='How well specializations match')),
                ('final_score', models.FloatField(help_text='Weighted combination of all scores')),
                ('match_reasoning', models.TextField(help_text='Why this is a good match')),
                ('rank', models.IntegerField(help_text='Ranking position in the match list')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('contacted', models.BooleanField(default=False)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_matches', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_matches', to='accounts.therapistprofile')),
            ],
            options={
                'db_table': 'therapist_matches',
                'ordering': ['rank'],
                'unique_together': {('patient', 'therapist', 'matched_at')},
            },
        ),
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('helpful_factors', models.JSONField(blank=True, help_text='What made this a good match', null=True)),
                ('unhelpful_factors', models.JSONField(blank=True, help_text='What made this a poor match', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.therapistmatch')),
            ],
            options={
                'db_table': 'match_feedback',
            },
        ),
        migrations.CreateModel(
            name='TherapistMatchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_text', models.TextField(help_text='Combined text representation of therapist profile')),
                ('profile_vector', models.JSONField(blank=True, help_text='TF-IDF vector representation', null=True)),
                ('blog_themes', models.JSONField(blank=True, help_text='Key themes extracted from therapist blogs', null=True)),
                ('last_blog_processed', models.DateTimeField(blank=True, help_text='Last time blogs were processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to='accounts.therapistprofile')),
            ],
            options={
                'db_table': 'therapist_match_profiles',
            },
        ),
    ]
