# Generated by Django 4.2.27 on 2026-02-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinglog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientmatchprofile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientmatchprofile',
            name='survey',
        ),
        migrations.AlterUniqueTogether(
            name='therapistmatch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='therapistmatch',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='therapistmatch',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='therapistmatchprofile',
            name='therapist',
        ),
        migrations.DeleteModel(
            name='MatchFeedback',
        ),
        migrations.DeleteModel(
            name='MatchingLog',
        ),
        migrations.DeleteModel(
            name='PatientMatchProfile',
        ),
        migrations.DeleteModel(
            name='TherapistMatch',
        ),
        migrations.DeleteModel(
            name='TherapistMatchProfile',
        ),
    ]
