# Generated by Django 4.2.27 on 2026-02-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0004_alter_survey_assessment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0002_remove_matchinglog_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_match_1_score', models.FloatField(default=0.0)),
                ('top_match_2_score', models.FloatField(default=0.0)),
                ('top_match_3_score', models.FloatField(default=0.0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_matches', to=settings.AUTH_USER_MODEL)),
                ('survey_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_match', to='surveys.surveyresponse')),
                ('top_match_1', models.ForeignKey(limit_choices_to={'role': 'therapist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_first', to=settings.AUTH_USER_MODEL)),
                ('top_match_2', models.ForeignKey(blank=True, limit_choices_to={'role': 'therapist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_second', to=settings.AUTH_USER_MODEL)),
                ('top_match_3', models.ForeignKey(blank=True, limit_choices_to={'role': 'therapist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_third', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist Match',
                'verbose_name_plural': 'Therapist Matches',
            },
        ),
    ]
