# Generated by Django 6.0 on 2026-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistmatch',
            name='match_reasons',
            field=models.JSONField(blank=True, default=dict, help_text='Stores match reasons for each therapist'),
        ),
    ]
