# Generated by Django 4.2.27 on 2026-02-04 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('answer_yes_no', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
                'ordering': ['response', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice (Radio Buttons)'), ('rating', 'Rating Scale'), ('yes_no', 'Yes/No Question'), ('text', 'Text Input')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('rating_min', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_max', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_min_label', models.CharField(blank=True, max_length=100)),
                ('rating_max_label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('option_text', models.CharField(max_length=255)),
                ('option_value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Scoring value for assessment matching', null=True)),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'multiple_choice'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.surveyquestion')),
            ],
            options={
                'verbose_name': 'Survey Question Option',
                'verbose_name_plural': 'Survey Question Options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed by Therapist')], default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='analysis_summary',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.AddField(
            model_name='survey',
            name='assessment_type',
            field=models.CharField(choices=[('standard', 'Standard Mental Health Assessment'), ('custom', 'Custom Therapist Matching Assessment'), ('both', 'Combined Assessment')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='No description provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='survey',
            table=None,
        ),
        migrations.DeleteModel(
            name='DynamicQuestionHistory',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.surveyquestionoption'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('patient', 'survey', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('response', 'question')},
        ),
    ]
