# Generated by Django 4.2.27 on 2026-02-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyanswer_surveyquestion_surveyquestionoption_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, help_text='The question whose answer triggers this question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_level',
            field=models.CharField(choices=[('static', 'Static Question'), ('dynamic', 'Dynamic/Conditional Question')], default='static', help_text='Static questions always shown; dynamic appear based on answers', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='trigger_condition',
            field=models.CharField(blank=True, help_text="The answer value that triggers this question (e.g., 'trauma' or 'very_distressed')", max_length=255),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='is_latest',
            field=models.BooleanField(default=True, help_text="Whether this is the patient's latest response"),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='retake_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this patient has retaken this survey'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['patient', 'survey', 'is_latest'], name='surveys_sur_patient_59ec60_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['patient', 'is_latest'], name='surveys_sur_patient_b21f76_idx'),
        ),
    ]
