# Generated by Django 4.2.27 on 2026-02-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveyresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='assessment_type',
            field=models.CharField(choices=[('standard', 'Standard Mental Health Assessment'), ('custom', 'Custom Therapist Matching Assessment'), ('both', 'Combined Assessment')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='trigger_condition',
            field=models.CharField(blank=True, help_text='The answer value that triggers this question', max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.surveyquestion'),
        ),
        migrations.AlterField(
            model_name='surveyquestionoption',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
