# Generated by Django 4.2.27 on 2026-02-15 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0004_alter_survey_assessment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalSurveyTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('trigger_reason', models.TextField(help_text="Why this survey was triggered (e.g., 'Mentioned anxiety in open-ended question')")),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Conditional Survey Trigger',
                'verbose_name_plural': 'Conditional Survey Triggers',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['stage_order', '-created'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AddField(
            model_name='survey',
            name='clinical_instrument',
            field=models.CharField(choices=[('none', 'Not a Clinical Instrument'), ('phq9', 'PHQ-9 (Depression)'), ('gad7', 'GAD-7 (Anxiety)'), ('pcl5', 'PCL-5 (PTSD)'), ('pc_ptsd5', 'PC-PTSD-5 (PTSD Screener)'), ('k10', 'K10 (Psychological Distress)'), ('sds', 'Sheehan Disability Scale')], default='none', help_text='If this survey is a validated clinical instrument, specify which one', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_conditional',
            field=models.BooleanField(default=False, help_text='If True, this survey is only shown based on previous answers'),
        ),
        migrations.AddField(
            model_name='survey',
            name='stage',
            field=models.CharField(blank=True, choices=[('preferences', 'Stage 1: Basic Preferences'), ('screening', 'Stage 2: Initial Screening'), ('clinical', 'Stage 3: Clinical Assessment'), ('functional', 'Stage 4: Functional Assessment'), ('matching', 'Stage 5: Therapist Preferences')], help_text='Which stage of the assessment this survey belongs to', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='stage_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this stage should be presented (0 = first)'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='clinical_score',
            field=models.IntegerField(default=0, help_text='Clinical score value for this answer'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='clinical_weight',
            field=models.IntegerField(default=0, help_text='Weight/points for clinical scoring (used in PHQ-9, GAD-7, etc.)'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='nlp_trigger_keywords',
            field=models.JSONField(blank=True, default=list, help_text="Keywords in open-ended answers that trigger this question (e.g., ['anxiety', 'panic', 'worried'])"),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='severity_threshold',
            field=models.IntegerField(blank=True, help_text='If parent question is a rating/score, trigger this question if score >= threshold', null=True),
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='clinical_score',
            field=models.IntegerField(default=0, help_text="Clinical score for this option (e.g., 0='Not at all', 3='Nearly every day')"),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='anxiety_severity',
            field=models.CharField(blank=True, choices=[('none', 'None/Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='crisis_flag',
            field=models.BooleanField(default=False, help_text='Flagged for immediate crisis intervention'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='depression_severity',
            field=models.CharField(blank=True, choices=[('none', 'None/Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='extracted_concerns',
            field=models.JSONField(blank=True, default=list, help_text='Automatically extracted concerns from open-ended answers'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='gad7_score',
            field=models.IntegerField(blank=True, help_text='GAD-7 anxiety score (0-21)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='k10_score',
            field=models.IntegerField(blank=True, help_text='K10 psychological distress score (10-50)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='pcl5_score',
            field=models.IntegerField(blank=True, help_text='PCL-5 PTSD score (0-80)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='phq9_score',
            field=models.IntegerField(blank=True, help_text='PHQ-9 depression score (0-27)', null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='suicide_risk_flag',
            field=models.BooleanField(default=False, help_text='Flagged for suicidal ideation'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice (Radio Buttons)'), ('rating', 'Rating Scale'), ('yes_no', 'Yes/No Question'), ('text', 'Text Input'), ('likert', 'Likert Scale (Not at all → Nearly every day)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['crisis_flag', 'suicide_risk_flag'], name='surveys_sur_crisis__e89461_idx'),
        ),
        migrations.AddField(
            model_name='conditionalsurveytrigger',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_triggers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conditionalsurveytrigger',
            name='survey',
            field=models.ForeignKey(limit_choices_to={'is_conditional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='conditionalsurveytrigger',
            name='triggered_by_response',
            field=models.ForeignKey(help_text='The survey response that triggered this conditional survey', on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='conditionalsurveytrigger',
            unique_together={('patient', 'survey', 'triggered_by_response')},
        ),
    ]
