# Generated by Django 4.2.27 on 2026-02-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_conditionalsurveytrigger_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditionalsurveytrigger',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conditionalsurveytrigger',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='conditionalsurveytrigger',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='conditionalsurveytrigger',
            name='triggered_by_response',
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='surveys_sur_crisis__e89461_idx',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='clinical_instrument',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_conditional',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='stage_order',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='clinical_score',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='clinical_weight',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='nlp_trigger_keywords',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='severity_threshold',
        ),
        migrations.RemoveField(
            model_name='surveyquestionoption',
            name='clinical_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='anxiety_severity',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='crisis_flag',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='depression_severity',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='extracted_concerns',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='gad7_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='k10_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='pcl5_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='phq9_score',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='suicide_risk_flag',
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice (Radio Buttons)'), ('rating', 'Rating Scale'), ('yes_no', 'Yes/No Question'), ('text', 'Text Input')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ConditionalSurveyTrigger',
        ),
    ]
