# Generated by Django 4.2.27 on 2026-02-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_assessment_type_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='survey_response',
            field=models.ForeignKey(blank=True, help_text='Patient assessment attached to this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='surveys.surveyresponse'),
        ),
    ]
