# Generated by Django 4.2.27 on 2026-02-07 16:53

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_survey_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assessment_file',
            field=models.FileField(blank=True, help_text='Patient can upload their assessment report (PDF, JSON, etc.)', null=True, upload_to=booking.models.assessment_file_path, verbose_name='Attached Assessment File'),
        ),
    ]
