# Generated by Django 4.2.27 on 2026-02-08 02:34

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_assessment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assessment_file',
            field=models.FileField(blank=True, help_text='Patient assessment file (PDF, TXT, DOCX)', null=True, upload_to=booking.models.assessment_upload_path),
        ),
    ]
