# Generated by Django 4.2.27 on 2026-02-11 14:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_alter_appointment_status_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist')], help_text='Whether the review is from patient or therapist', max_length=10)),
                ('rating', models.IntegerField(help_text='Rating from 1 (poor match/experience) to 10 (excellent match/experience)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review_text', models.TextField(help_text='Detailed feedback about the appointment and match quality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.appointment')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Review',
                'verbose_name_plural': 'Appointment Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment', 'reviewer_type'], name='booking_app_appoint_7a64a4_idx'), models.Index(fields=['reviewed_user', 'reviewer_type'], name='booking_app_reviewe_ff7efe_idx')],
                'unique_together': {('appointment', 'reviewer')},
            },
        ),
    ]
