# Generated by Django 4.2.27 on 2026-02-15 02:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_appointmentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_summary', models.TextField(help_text='What was discussed in this session')),
                ('mood_rating', models.IntegerField(help_text='Patient mood/emotional state during session (1=very negative, 10=very positive)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('symptom_improvement', models.JSONField(blank=True, default=dict, help_text='Tracking symptom improvements: {"anxiety": 7, "depression": 5, ...}')),
                ('treatment_goals_addressed', models.JSONField(blank=True, default=list, help_text='List of treatment goals addressed in this session')),
                ('session_outcome', models.CharField(choices=[('productive', 'Productive Session'), ('breakthrough', 'Breakthrough Moment'), ('needs_follow_up', 'Needs Follow-Up'), ('blocked', 'Blocked/Stuck')], default='productive', help_text='Overall outcome of the session', max_length=20)),
                ('homework_assigned', models.TextField(blank=True, help_text='Assignments or homework for patient to complete before next session')),
                ('triggers_identified', models.TextField(blank=True, help_text='Triggers or patterns identified during session')),
                ('notes_for_next_session', models.TextField(blank=True, help_text='Topics, focus areas, or notes for the next session')),
                ('clinical_observations', models.TextField(blank=True, help_text='Clinical observations or progress notes from therapist')),
                ('patient_visible', models.BooleanField(default=False, help_text='If True, patient can see anonymized summary of this report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(help_text='The appointment this report is for', on_delete=django.db.models.deletion.CASCADE, related_name='session_report', to='booking.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_reports_received', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_reports_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'created_at'], name='session_rep_therapi_1cb859_idx'), models.Index(fields=['patient', 'created_at'], name='session_rep_patient_a55fcd_idx'), models.Index(fields=['appointment'], name='session_rep_appoint_129e1b_idx')],
            },
        ),
    ]
