# Generated by Django 4.2.27 on 2026-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_sessionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recording_sid',
            field=models.CharField(blank=True, help_text='Agora recording ID if recorded', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Actual session duration', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_ended_at',
            field=models.DateTimeField(blank=True, help_text='When video session ended', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_started_at',
            field=models.DateTimeField(blank=True, help_text='When video session actually started', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_channel_name',
            field=models.CharField(blank=True, help_text='Agora channel name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_token_patient',
            field=models.TextField(blank=True, help_text='Agora token for patient', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_token_therapist',
            field=models.TextField(blank=True, help_text='Agora token for therapist', null=True),
        ),
    ]
