# Generated by Django 4.2.27 on 2026-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_appointment_recording_sid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['video_channel_name'], name='appointment_video_c_2748bf_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['session_started_at'], name='appointment_session_6cde70_idx'),
        ),
    ]
